import argparse
import calendar
import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone

from openpyxl import load_workbook
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.runtime import maintenance_mode_enabled


logger = logging.getLogger(__name__)

DAY_WORKDAY = "workday"
DAY_WEEKEND = "weekend"
DAY_HOLIDAY = "official_holiday"
DAY_TRANSFERRED_OFF = "transferred_day_off"
DAY_WORKING_SATURDAY = "working_saturday"
DAY_MANUAL = "manual_override"
DAY_TYPES = {
    DAY_WORKDAY,
    DAY_WEEKEND,
    DAY_HOLIDAY,
    DAY_TRANSFERRED_OFF,
    DAY_WORKING_SATURDAY,
    DAY_MANUAL,
}

GOVERNMENT_2025_URL = "https://government.ru/docs/all/155500/"
GOVERNMENT_2026_URL = "https://government.ru/docs/all/161028/"
PRAVO_2026_URL = "https://publication.pravo.gov.ru/document/0001202509240023"


CALENDAR_DDL = """
CREATE TABLE IF NOT EXISTS production_calendar (
    calendar_date DATE PRIMARY KEY,
    is_day_off BOOLEAN NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    comment TEXT NOT NULL DEFAULT '',
    year INTEGER NOT NULL,
    source TEXT NOT NULL DEFAULT 'admin',
    day_type TEXT NOT NULL DEFAULT 'workday',
    synced_at TIMESTAMPTZ,
    is_manual_override BOOLEAN NOT NULL DEFAULT FALSE,
    manual_comment TEXT NOT NULL DEFAULT '',
    official_is_day_off BOOLEAN,
    official_title TEXT NOT NULL DEFAULT '',
    official_day_type TEXT NOT NULL DEFAULT '',
    official_source TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""

SYNC_DDL = """
CREATE TABLE IF NOT EXISTS production_calendar_sync (
    year INTEGER PRIMARY KEY,
    status TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT '',
    source_published_at DATE,
    last_success_at TIMESTAMPTZ,
    row_count INTEGER NOT NULL DEFAULT 0,
    message TEXT NOT NULL DEFAULT ''
)
"""

AUDIT_DDL = """
CREATE TABLE IF NOT EXISTS production_calendar_audit (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    calendar_date DATE NOT NULL,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    changed_fields TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""


@dataclass(frozen=True)
class OfficialCalendarManifest:
    year: int
    decree: str
    source_url: str
    published_at: date
    transferred_days_off: tuple[date, ...]
    working_weekends: tuple[date, ...] = ()


OFFICIAL_MANIFESTS = {
    2025: OfficialCalendarManifest(
        year=2025,
        decree="Постановление Правительства РФ от 04.10.2024 № 1335",
        source_url=GOVERNMENT_2025_URL,
        published_at=date(2024, 10, 4),
        transferred_days_off=(
            date(2025, 5, 2),
            date(2025, 5, 8),
            date(2025, 6, 13),
            date(2025, 11, 3),
            date(2025, 12, 31),
        ),
        working_weekends=(date(2025, 11, 1),),
    ),
    2026: OfficialCalendarManifest(
        year=2026,
        decree="Постановление Правительства РФ от 24.09.2025 № 1466",
        source_url=PRAVO_2026_URL,
        published_at=date(2025, 9, 24),
        transferred_days_off=(
            date(2026, 1, 9),
            date(2026, 3, 9),
            date(2026, 5, 11),
            date(2026, 12, 31),
        ),
    ),
}

STATUTORY_HOLIDAYS = {
    (1, 1): "Новогодние каникулы",
    (1, 2): "Новогодние каникулы",
    (1, 3): "Новогодние каникулы",
    (1, 4): "Новогодние каникулы",
    (1, 5): "Новогодние каникулы",
    (1, 6): "Новогодние каникулы",
    (1, 7): "Рождество Христово",
    (1, 8): "Новогодние каникулы",
    (2, 23): "День защитника Отечества",
    (3, 8): "Международный женский день",
    (5, 1): "Праздник Весны и Труда",
    (5, 9): "День Победы",
    (6, 12): "День России",
    (11, 4): "День народного единства",
}


def _dialect_name(db: Session) -> str:
    return getattr(getattr(getattr(db, "bind", None), "dialect", None), "name", "")


def ensure_production_calendar_table(db: Session, *, commit: bool = True) -> None:
    if maintenance_mode_enabled():
        return
    db.execute(text(CALENDAR_DDL))
    dialect = _dialect_name(db)
    if dialect == "postgresql":
        additions = (
            "comment TEXT NOT NULL DEFAULT ''",
            "day_type TEXT NOT NULL DEFAULT 'workday'",
            "synced_at TIMESTAMPTZ",
            "is_manual_override BOOLEAN NOT NULL DEFAULT FALSE",
            "manual_comment TEXT NOT NULL DEFAULT ''",
            "official_is_day_off BOOLEAN",
            "official_title TEXT NOT NULL DEFAULT ''",
            "official_day_type TEXT NOT NULL DEFAULT ''",
            "official_source TEXT NOT NULL DEFAULT ''",
        )
        for definition in additions:
            db.execute(text(
                f"ALTER TABLE production_calendar ADD COLUMN IF NOT EXISTS {definition}"
            ))
    db.execute(text(SYNC_DDL))
    if dialect == "sqlite":
        db.execute(text("""
            CREATE TABLE IF NOT EXISTS production_calendar_audit (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                calendar_date DATE NOT NULL,
                action TEXT NOT NULL,
                actor TEXT NOT NULL,
                changed_fields TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """))
    else:
        db.execute(text(AUDIT_DDL))
    if commit:
        db.commit()


def calendar_day_off(current_date: date, overrides: dict[date, bool]) -> bool:
    """Stored official/manual data overrides the normal Saturday/Sunday rule."""
    if current_date in overrides:
        return bool(overrides[current_date])
    return current_date.weekday() >= 5


def get_calendar_overrides(db: Session, year: int, month: int) -> dict[date, bool]:
    ensure_production_calendar_table(db, commit=False)
    dialect = _dialect_name(db)
    month_predicate = (
        "EXTRACT(MONTH FROM calendar_date)=:month"
        if dialect == "postgresql"
        else "CAST(strftime('%m', calendar_date) AS INTEGER)=:month"
    )
    rows = db.execute(text(f"""
        SELECT calendar_date, is_day_off FROM production_calendar
        WHERE year=:year AND {month_predicate}
    """), {"year": year, "month": month}).all()
    return {row[0] if isinstance(row[0], date) else date.fromisoformat(row[0]): bool(row[1]) for row in rows}


def build_official_calendar(year: int) -> list[dict]:
    manifest = OFFICIAL_MANIFESTS.get(year)
    if not manifest:
        raise ValueError(f"Официальный календарь за {year} год ещё не утверждён или не встроен")
    transferred = set(manifest.transferred_days_off)
    working_weekends = set(manifest.working_weekends)
    current = date(year, 1, 1)
    end = date(year, 12, 31)
    rows = []
    while current <= end:
        holiday_title = STATUTORY_HOLIDAYS.get((current.month, current.day), "")
        if current in working_weekends:
            is_day_off, day_type, title = False, DAY_WORKING_SATURDAY, "Рабочая суббота"
        elif current in transferred:
            is_day_off, day_type, title = True, DAY_TRANSFERRED_OFF, "Перенесённый выходной"
        elif holiday_title:
            is_day_off, day_type, title = True, DAY_HOLIDAY, holiday_title
        elif current.weekday() >= 5:
            is_day_off, day_type, title = True, DAY_WEEKEND, ""
        else:
            is_day_off, day_type, title = False, DAY_WORKDAY, ""
        rows.append({
            "calendar_date": current,
            "is_day_off": is_day_off,
            "title": title,
            "comment": "",
            "year": year,
            "source": f"{manifest.decree}; {manifest.source_url}",
            "day_type": day_type,
            "synced_at": datetime.now(timezone.utc),
            "official_is_day_off": is_day_off,
            "official_title": title,
            "official_day_type": day_type,
            "official_source": f"{manifest.decree}; {manifest.source_url}",
        })
        current += timedelta(days=1)
    validate_official_calendar(rows, year)
    return rows


def validate_official_calendar(rows: list[dict], year: int) -> None:
    expected = 366 if calendar.isleap(year) else 365
    dates = [row["calendar_date"] for row in rows]
    if len(rows) != expected or len(set(dates)) != expected:
        raise ValueError(f"Календарь {year}: ожидается {expected} уникальных дат")
    if min(dates) != date(year, 1, 1) or max(dates) != date(year, 12, 31):
        raise ValueError(f"Календарь {year}: диапазон дат неполный")
    if any(item.year != year for item in dates):
        raise ValueError(f"Календарь {year}: обнаружена дата другого года")
    invalid_types = {row["day_type"] for row in rows} - DAY_TYPES
    if invalid_types:
        raise ValueError(f"Календарь {year}: неизвестные типы {sorted(invalid_types)}")
    if not any(row["is_day_off"] for row in rows) or not any(not row["is_day_off"] for row in rows):
        raise ValueError(f"Календарь {year}: отсутствуют рабочие или нерабочие дни")
    holiday_count = sum(row["day_type"] == DAY_HOLIDAY for row in rows)
    if holiday_count < len(STATUTORY_HOLIDAYS):
        raise ValueError(f"Календарь {year}: слишком мало официальных праздников")


def sync_calendar_year(db: Session, year: int) -> dict:
    manifest = OFFICIAL_MANIFESTS.get(year)
    rows = build_official_calendar(year)
    try:
        ensure_production_calendar_table(db, commit=False)
        db.execute(text("""
            INSERT INTO production_calendar (
                calendar_date, is_day_off, title, comment, year, source, day_type,
                synced_at, official_is_day_off, official_title, official_day_type,
                official_source
            ) VALUES (
                :calendar_date, :is_day_off, :title, :comment, :year, :source, :day_type,
                :synced_at, :official_is_day_off, :official_title, :official_day_type,
                :official_source
            )
            ON CONFLICT (calendar_date) DO UPDATE SET
                is_day_off=CASE WHEN production_calendar.is_manual_override
                    THEN production_calendar.is_day_off ELSE EXCLUDED.is_day_off END,
                title=CASE WHEN production_calendar.is_manual_override
                    THEN production_calendar.title ELSE EXCLUDED.title END,
                source=CASE WHEN production_calendar.is_manual_override
                    THEN production_calendar.source ELSE EXCLUDED.source END,
                day_type=CASE WHEN production_calendar.is_manual_override
                    THEN production_calendar.day_type ELSE EXCLUDED.day_type END,
                year=EXCLUDED.year,
                synced_at=EXCLUDED.synced_at,
                official_is_day_off=EXCLUDED.official_is_day_off,
                official_title=EXCLUDED.official_title,
                official_day_type=EXCLUDED.official_day_type,
                official_source=EXCLUDED.official_source,
                updated_at=CURRENT_TIMESTAMP
        """), rows)
        db.execute(text("""
            INSERT INTO production_calendar_sync (
                year, status, source, source_published_at, last_success_at, row_count, message
            ) VALUES (
                :year, 'success', :source, :published, CURRENT_TIMESTAMP, :count, :message
            )
            ON CONFLICT (year) DO UPDATE SET
                status='success',
                source=EXCLUDED.source,
                source_published_at=EXCLUDED.source_published_at,
                last_success_at=CURRENT_TIMESTAMP,
                row_count=EXCLUDED.row_count,
                message=EXCLUDED.message
        """), {
            "year": year,
            "source": manifest.source_url,
            "published": manifest.published_at,
            "count": len(rows),
            "message": manifest.decree,
        })
        db.commit()
    except Exception:
        db.rollback()
        raise
    return {"year": year, "loaded_rows": len(rows), "source": manifest.source_url}


def sync_approved_calendars(db: Session, years: list[int] | None = None) -> dict:
    selected = years or [date.today().year, date.today().year + 1]
    approved = [year for year in selected if year in OFFICIAL_MANIFESTS]
    results = [sync_calendar_year(db, year) for year in approved]
    return {
        "synced_years": [result["year"] for result in results],
        "loaded_rows": sum(result["loaded_rows"] for result in results),
        "unavailable_years": [year for year in selected if year not in OFFICIAL_MANIFESTS],
    }


def get_calendar_status(db: Session) -> list[dict]:
    ensure_production_calendar_table(db, commit=False)
    return [
        dict(row)
        for row in db.execute(text("""
            SELECT year, status, source, source_published_at, last_success_at, row_count, message
            FROM production_calendar_sync ORDER BY year DESC
        """)).mappings().all()
    ]


def set_manual_calendar_override(
    db: Session,
    calendar_date: date,
    is_day_off: bool,
    title: str,
    comment: str,
    *,
    actor: str,
) -> None:
    if not comment.strip():
        raise ValueError("Для ручной корректировки нужен комментарий")
    ensure_production_calendar_table(db, commit=False)
    db.execute(text("""
        INSERT INTO production_calendar (
            calendar_date, is_day_off, title, comment, year, source, day_type,
            is_manual_override, manual_comment
        ) VALUES (
            :day, :off, :title, :comment, :year, 'manual', :day_type, TRUE, :comment
        )
        ON CONFLICT (calendar_date) DO UPDATE SET
            is_day_off=EXCLUDED.is_day_off,
            title=EXCLUDED.title,
            comment=EXCLUDED.comment,
            source='manual',
            day_type=:day_type,
            is_manual_override=TRUE,
            manual_comment=EXCLUDED.manual_comment,
            updated_at=CURRENT_TIMESTAMP
    """), {
        "day": calendar_date,
        "off": is_day_off,
        "title": title.strip(),
        "comment": comment.strip(),
        "year": calendar_date.year,
        "day_type": DAY_MANUAL,
    })
    db.execute(text("""
        INSERT INTO production_calendar_audit
            (calendar_date, action, actor, changed_fields)
        VALUES (:day, 'manual_override', :actor, 'is_day_off,title,manual_comment')
    """), {"day": calendar_date, "actor": actor})
    db.commit()


def reset_manual_calendar_override(db: Session, calendar_date: date, *, actor: str) -> None:
    ensure_production_calendar_table(db, commit=False)
    result = db.execute(text("""
        UPDATE production_calendar SET
            is_day_off=official_is_day_off,
            title=official_title,
            source=official_source,
            day_type=official_day_type,
            is_manual_override=FALSE,
            manual_comment='',
            comment='',
            updated_at=CURRENT_TIMESTAMP
        WHERE calendar_date=:day
          AND is_manual_override=TRUE
          AND official_is_day_off IS NOT NULL
    """), {"day": calendar_date})
    if getattr(result, "rowcount", 0) != 1:
        db.rollback()
        raise ValueError("Для даты нет официального значения, к которому можно вернуться")
    db.execute(text("""
        INSERT INTO production_calendar_audit
            (calendar_date, action, actor, changed_fields)
        VALUES (:day, 'reset_to_official', :actor, 'is_day_off,title,manual_comment')
    """), {"day": calendar_date, "actor": actor})
    db.commit()


def _bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    normalized = str(value or "").strip().lower().replace("ё", "е")
    if normalized in {"1", "true", "yes", "да", "выходной", "нерабочий"}:
        return True
    if normalized in {"0", "false", "no", "нет", "рабочий"}:
        return False
    raise ValueError(f"invalid day-off flag: {value!r}")


def parse_calendar_workbook(file_obj) -> list[dict]:
    workbook = load_workbook(file_obj, read_only=True, data_only=True)
    sheet = workbook.active
    iterator = sheet.iter_rows(values_only=True)
    try:
        headers = next(iterator)
    except StopIteration:
        raise ValueError("Файл производственного календаря пуст")
    normalized = {
        " ".join(str(value or "").strip().lower().replace("ё", "е").split()): index
        for index, value in enumerate(headers)
    }
    aliases = {
        "calendar_date": ("calendar_date", "дата"),
        "is_day_off": ("is_day_off", "выходной", "выходной день", "нерабочий день"),
        "title": ("title", "название"),
        "source": ("source", "источник"),
        "comment": ("comment", "комментарий", "примечание"),
    }
    indexes = {}
    for canonical, names in aliases.items():
        for name in names:
            if name in normalized:
                indexes[canonical] = normalized[name]
                break
    missing = {"calendar_date", "is_day_off"} - indexes.keys()
    if missing:
        raise ValueError(f"Нет обязательных колонок: {', '.join(sorted(missing))}")
    result, seen = [], set()
    for row_number, row in enumerate(iterator, start=2):
        if not any(value not in (None, "") for value in row):
            continue
        try:
            raw_date = row[indexes["calendar_date"]]
            calendar_date = raw_date.date() if isinstance(raw_date, datetime) else (
                raw_date if isinstance(raw_date, date) else date.fromisoformat(str(raw_date)[:10])
            )
            if calendar_date in seen:
                raise ValueError("дата повторяется")
            seen.add(calendar_date)
            result.append({
                "calendar_date": calendar_date,
                "is_day_off": _bool(row[indexes["is_day_off"]]),
                "title": str(row[indexes["title"]] or "").strip() if "title" in indexes else "",
                "comment": str(row[indexes["comment"]] or "").strip() if "comment" in indexes else "",
                "year": calendar_date.year,
                "source": str(row[indexes["source"]] or "admin").strip() if "source" in indexes else "admin",
                "day_type": DAY_MANUAL,
                "is_manual_override": True,
                "manual_comment": (
                    str(row[indexes["comment"]] or "").strip()
                    if "comment" in indexes else "Аварийный XLSX-импорт"
                ),
            })
        except (ValueError, TypeError, IndexError) as exc:
            raise ValueError(f"Ошибка в строке {row_number}: {exc}") from exc
    if not result:
        raise ValueError("В файле нет дат")
    return result


def import_calendar_xlsx(db: Session, file_obj) -> dict:
    rows = parse_calendar_workbook(file_obj)
    try:
        ensure_production_calendar_table(db, commit=False)
        db.execute(text("""
            INSERT INTO production_calendar (
                calendar_date, is_day_off, title, comment, year, source, day_type,
                is_manual_override, manual_comment
            ) VALUES (
                :calendar_date, :is_day_off, :title, :comment, :year, :source, :day_type,
                :is_manual_override, :manual_comment
            )
            ON CONFLICT (calendar_date) DO UPDATE SET
                is_day_off=EXCLUDED.is_day_off,
                title=EXCLUDED.title,
                comment=EXCLUDED.comment,
                year=EXCLUDED.year,
                source=EXCLUDED.source,
                day_type=EXCLUDED.day_type,
                is_manual_override=TRUE,
                manual_comment=EXCLUDED.manual_comment,
                updated_at=CURRENT_TIMESTAMP
        """), rows)
        db.commit()
    except Exception:
        db.rollback()
        raise
    return {"loaded_rows": len(rows), "years": sorted({row["year"] for row in rows})}


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync approved Russian production calendars")
    parser.add_argument("--year", type=int, action="append", help="approved year; may be repeated")
    args = parser.parse_args()
    from app.db import SessionLocal

    db = SessionLocal()
    try:
        result = sync_approved_calendars(db, args.year)
        print(
            f"synced_years={result['synced_years']} "
            f"loaded_rows={result['loaded_rows']} "
            f"unavailable_years={result['unavailable_years']}"
        )
    finally:
        db.close()


if __name__ == "__main__":
    main()
